sudo: required
language: python
services:
- docker
python:
- 3.6

cache:
  directories:
    - "${HOME}/google-cloud-sdk/"

before_install:
  - ./travis/install-git-crypt.bash

install:
  - pip install --no-cache-dir pyyaml

script:
- "./travis/travis-script.bash build"

branches:
  only:
    - staging
    - prod

deploy:
  provider: script
  script: ./travis/travis-script.bash deploy
  on:
    branch:
      - staging
      - prod

env:
  global:
    - GCLOUD_PROJECT="striped-acrobat-186800" 
    - HUB_COURSE="prob140"
    - secure: chqbKnXbvZcOiKHxozw9TNxMTm85NsyURhSDaEyLNAKGBfS/1If0wDm83cshvJRrGcAxcosaEU0eAdeI5PV9ZtGIxbrIaizj2UPvq1yDPLhAepHqgP4Nm1bFf+zfEyWbcNmqJfwKdRQtw3GWi/aKkQzZcShENJDJahwcoiGugkwlnTDLulyBGCK5XCfUKUFnyXln75LsM/a/0tLeG/lpCgTt7cOX9pPqWkaNYkYWs6e8aeBU71FasVSQ6fkDpRSdD5ezFsfbU/L7Fv+O7h0YQf+4Q1WB4PibdZgWufDIcsQQkOlDcm9zu4Djj+v38CugKXSKjEO7qpgIsoft3eDipKOMuZO/BM5jNX2ix/LGQwf+AgDZES0ERQXsZ++PUeWvl8m1CgqYaUkoGvCFo19tfYJiPbn5UwsFawaMW/BjxuvtFsXWV21VJl1YlqKZvegwfzdg7sjJ2ExFF0tBGwecJ0u0zvlGkb2IBjFk11NpZ6L9NJMDLNOM03QVw13p9TTbhIVpCSsEPjZFAzBfg5cHUnicWqdiZbCpv4VY/HLOY3mm+MoKAv2tZ23Dqhi5+lyG2yYKpbyFpCf1C/SLn48Eza4UhMWkcbJ6k08U4iEhR0o5H8F6OZwhBs8OTCGfwaIDUa9fB1IFgeJb0mvwK1xWSIkM4V+EKAGiOcf9Z9ZRytg=
    - secure: CPKgoIPU8lhjym7jkP3v2Wc3633C7/YZZFWVBjVddqeSkaItrnhShfW0Y6ugqSZZHwqHnGO/LxNcwZAI+o1LAl0oWleO/bpacTzD4OKkU8YsV7pvCok5y8SgW+v4zzN10K/ZfIB/z4ikDmEiO8jlOPRrRGVUpCaKbcXkXb9Wf/wB7nNL3gvBsOpIBoDnqZaoOQDLC3x3XczflFwpPtTZvWA8ajRkqVyEB4eGXpONMxrHijLe0U87wDFKxai8w5078nPmn3jhbdjQxbvZdC4X1FiIrPGIgNLevGvqx0O4khxPUAKmT2fGYoSbRUnCv/sB3UKQo5H8UlYHzirfRNeeIksWLKjx0sdx1YV1SqWmUNZs+ToGEOiV7tQn2DgKnNUJYuJ1vuhzaxCGLMDeYCUQYc5meDfKHyFGZDJZKOI27AiQrubNzLc9sBdmDoyjj7nT00u0juzAGuCFuZeHMbICm4UUhjHIEuBeEs5P26IPrUSKum+Yn+ppshQXHSzy2GfOMX+j6InNEFbOCv1UeDckvrcLYgGL8z3WVKtc5rLwiQQamRR11aWv1QeHH8rEuYTfNGxTOPn36cdYB+jBwf7NKTiRrUCPbYoAeq4W69Jxg7yil6Ui+06fVXXVLrbXY6/N+NGZ1THTabgfUbp1dHJrNaCpJJeh54H3/S/Sf+in9L4=
