kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hotspare
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["watch", "list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hotspare
subjects:
- kind: ServiceAccount
  namespace: staging
  name: hotspare
roleRef:
  kind: ClusterRole
  name: hotspare
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hotspare
